rbac:
  create: false
  pspEnabled: false

serviceAccount:
  create: false

persistence:
  type: pvc
  enabled: true
  storageClassName: "\"\""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

initChownData:
  enabled: false

priorityClassName: uber-user-preempt-high

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nvidia.com/gpu.count
          operator: DoesNotExist
